### ISSUE TITLE
전체적으로 잘하셨습니다.

### ISSUE THREAD

**Issue by junkwon-dev** [daily1313/Board#10]
테스트코드도 짜시고 docker image까지 만드신거 보면 한 플로우는 잘 만드셨네요.
디테일인건 회사도 아니고 개인 플젝인데 이정도면 꽤 신경써서 하신거같아요.
이대로만 공부하시면 될거같습니다

가능하면 DDD같은걸 학습하시는게 좋구요 - 백엔드
TDD도 ..(저도 잘 못하는 TDD)

minikube같은걸로 devops 맛봬기하는것도 좋습니다. - 데브옵스

백엔드 하시더라도 데브옵스 조금 경험하시는것도 엄청 큰 도움 되구요

**Comment by daily1313** [comment]
감사합니다. 조언에 맞게 다시 리펙토링 해보겠습니다.
